name: Deploy to ACI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          name: myapp
          resource-group: azresource
          dns-name-label: myapp${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/app:latest
          location: 'canadacentral'
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          registry-password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}      
          cpu: 1
          memory: 1.5
          ports: 80
